name: Generate UML Diagrams

on:
  push:
    branches:
      - main

jobs:
  generate-uml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Generate UML diagrams
      run: |
        pyreverse -o png -p MyProject .

    - name: Upload UML diagrams
      uses: actions/upload-artifact@v2
      with:
        name: uml-diagrams
        path: |
          ./classes_cms.png
          ./packages_cms.png